if (!globalThis.__SEEDPASS_CONTENT_SCRIPT_LOADED__) {
  globalThis.__SEEDPASS_CONTENT_SCRIPT_LOADED__ = true;

  let activeInput = null;
  let panel = null;
  let hideTimer = null;
  let selectedRecordId = null;
  let currentLanguage = "zh";

  const text = {
    zh: {
      title: "SeedPass",
      noVault: "请先点击插件图标创建本地保险库。",
      noRecord: "当前网站还没有保存的密码记录，请在插件面板添加。",
      unlocked: "已解锁，选择要填充的密码。",
      locked: "输入 6 位 PIN 后填充。",
      fill: "填充",
      domainMode: "按网站生成",
      accountMode: "按账号标识生成",
      unlocking: "正在解锁...",
      filled: "已填充。",
      requestFailed: "插件请求失败。"
    },
    en: {
      title: "SeedPass",
      noVault: "Open the extension first to create a local vault.",
      noRecord: "No saved password record for this site. Add one in the extension panel.",
      unlocked: "Unlocked. Choose a password to fill.",
      locked: "Enter your 6-digit PIN to fill.",
      fill: "Fill",
      domainMode: "Generated by site",
      accountMode: "Generated by account label",
      unlocking: "Unlocking...",
      filled: "Filled.",
      requestFailed: "Extension request failed."
    }
  };

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type !== "seedpass-fill") return false;
    const input = activeInput && isFillablePasswordInput(activeInput) ? activeInput : findPasswordInput();
    if (!input) {
      sendResponse({ filled: false });
      return true;
    }
    fillInput(input, message.password);
    hidePanel();
    sendResponse({ filled: true });
    return true;
  });

  document.addEventListener("focusin", (event) => {
    if (!isFillablePasswordInput(event.target)) return;
    activeInput = event.target;
    showSuggestion();
  });

  document.addEventListener("focusout", scheduleHide);
  window.addEventListener("scroll", positionPanel, true);
  window.addEventListener("resize", positionPanel);

  async function showSuggestion() {
    clearHideTimer();
    const state = await sendMessage({ type: "inline-state" }).catch((error) => ({
      ok: false,
      error: error.message
    }));
    currentLanguage = resolveLanguage(state.language);
    panel = panel ?? createPanel();
    renderPanel(state);
    positionPanel();
  }

  function renderPanel(state) {
    const t = text[currentLanguage];
    const title = panel.querySelector("[data-title]");
    const body = panel.querySelector("[data-body]");
    title.textContent = t.title;
    body.innerHTML = "";

    if (!state.ok) {
      body.append(textBlock(state.error || t.requestFailed));
      return;
    }
    if (!state.hasVault) {
      body.append(textBlock(t.noVault));
      return;
    }
    if (!state.records?.length) {
      body.append(textBlock(t.noRecord));
      return;
    }

    body.append(textBlock(state.unlocked ? t.unlocked : t.locked));
    for (const record of state.records) {
      body.append(recordButton(record, state.unlocked));
    }

    if (!state.unlocked) {
      body.append(pinInput(async (pin, status, boxes) => {
        status.textContent = t.unlocking;
        try {
          const response = await sendMessage({
            type: "inline-unlock-and-fill",
            recordId: selectedRecordId ?? state.records[0].id,
            pin,
            timeoutMinutes: state.defaultTimeoutMinutes
          });
          fillInput(activeInput, response.password);
          status.textContent = t.filled;
          setTimeout(hidePanel, 350);
        } catch (error) {
          status.textContent = error.message;
          boxes.forEach((box) => (box.value = ""));
          boxes[0]?.focus();
        }
      }));
    }
  }

  function recordButton(record, unlocked) {
    const t = text[currentLanguage];
    const button = document.createElement("button");
    button.type = "button";
    button.className = "seedpass-record-button";
    const title = record.accountLabel || record.siteIdentity;
    const note = record.note ? ` · ${record.note}` : "";
    const mode = record.mode === "account" ? t.accountMode : t.domainMode;
    button.innerHTML = `<strong></strong><span></span>`;
    button.querySelector("strong").textContent = title;
    button.querySelector("span").textContent = `${mode}${note}`;
    button.addEventListener("click", async () => {
      selectedRecordId = record.id;
      if (!unlocked) {
        panel.querySelector(".seedpass-pin-box")?.focus();
        return;
      }
      try {
        const response = await sendMessage({ type: "inline-fill", recordId: record.id });
        fillInput(activeInput, response.password);
        hidePanel();
      } catch (error) {
        renderPanel({ ok: false, error: error.message });
      }
    });
    return button;
  }

  function createPanel() {
    const root = document.createElement("div");
    root.id = "seedpass-inline-panel";
    root.innerHTML = `
      <style>
        #seedpass-inline-panel {
          background: #fffaf0;
          border: 1px solid rgba(55, 42, 24, 0.22);
          border-radius: 14px;
          box-shadow: 0 18px 50px rgba(25, 20, 12, 0.18);
          color: #1a1712;
          font-family: "Microsoft YaHei", "Noto Sans SC", sans-serif;
          font-size: 13px;
          max-width: 340px;
          padding: 10px;
          position: fixed;
          width: 300px;
          z-index: 2147483647;
        }
        #seedpass-inline-panel [data-title] {
          color: #9b4d15;
          font-size: 11px;
          font-weight: 800;
          letter-spacing: 0.12em;
          margin-bottom: 6px;
          text-transform: uppercase;
        }
        .seedpass-text {
          color: #5f503e;
          line-height: 1.45;
          margin-bottom: 8px;
        }
        .seedpass-record-button {
          background: rgba(29, 43, 36, 0.08);
          border: 1px solid rgba(29, 43, 36, 0.12);
          border-radius: 12px;
          color: #1a1712;
          cursor: pointer;
          display: grid;
          gap: 3px;
          margin: 6px 0;
          padding: 9px;
          text-align: left;
          width: 100%;
        }
        .seedpass-record-button:hover {
          background: rgba(29, 43, 36, 0.14);
        }
        .seedpass-record-button strong {
          font-size: 14px;
        }
        .seedpass-record-button span {
          color: #6a5942;
          font-size: 12px;
        }
        .seedpass-pin-row {
          display: flex;
          gap: 6px;
          margin-top: 8px;
        }
        .seedpass-pin-box {
          background: #fff;
          border: 1px solid rgba(55, 42, 24, 0.28);
          border-radius: 9px;
          box-sizing: border-box;
          font-size: 18px;
          height: 36px;
          text-align: center;
          width: 34px;
        }
        .seedpass-status {
          color: #9f1d16;
          font-size: 12px;
          margin-top: 7px;
          min-height: 16px;
        }
      </style>
      <div data-title></div>
      <div data-body></div>
    `;
    root.addEventListener("mousedown", (event) => {
      event.preventDefault();
      clearHideTimer();
    });
    document.documentElement.append(root);
    return root;
  }

  function pinInput(onComplete) {
    const wrapper = document.createElement("div");
    const row = document.createElement("div");
    const status = document.createElement("div");
    row.className = "seedpass-pin-row";
    status.className = "seedpass-status";
    const boxes = Array.from({ length: 6 }, () => {
      const box = document.createElement("input");
      box.type = "password";
      box.inputMode = "numeric";
      box.maxLength = 1;
      box.autocomplete = "off";
      box.className = "seedpass-pin-box";
      row.append(box);
      return box;
    });
    wirePinBoxes(boxes, (pin) => onComplete(pin, status, boxes));
    wrapper.append(row, status);
    setTimeout(() => boxes[0]?.focus(), 0);
    return wrapper;
  }

  function wirePinBoxes(boxes, onComplete) {
    boxes.forEach((box, index) => {
      box.addEventListener("input", () => {
        box.value = box.value.replace(/\D/g, "").slice(0, 1);
        if (box.value && index < boxes.length - 1) boxes[index + 1].focus();
        const pin = boxes.map((item) => item.value).join("");
        if (/^\d{6}$/.test(pin)) onComplete(pin);
      });
      box.addEventListener("keydown", (event) => {
        if (event.key === "Backspace" && !box.value && index > 0) boxes[index - 1].focus();
      });
    });
  }

  function positionPanel() {
    if (!panel || !activeInput || !isFillablePasswordInput(activeInput)) return;
    const rect = activeInput.getBoundingClientRect();
    const top = Math.min(rect.bottom + 8, window.innerHeight - panel.offsetHeight - 8);
    const left = Math.min(rect.left, window.innerWidth - panel.offsetWidth - 8);
    panel.style.top = `${Math.max(8, top)}px`;
    panel.style.left = `${Math.max(8, left)}px`;
  }

  function scheduleHide() {
    clearHideTimer();
    hideTimer = setTimeout(() => {
      if (!panel?.contains(document.activeElement)) hidePanel();
    }, 180);
  }

  function clearHideTimer() {
    if (hideTimer) clearTimeout(hideTimer);
    hideTimer = null;
  }

  function hidePanel() {
    clearHideTimer();
    panel?.remove();
    panel = null;
    selectedRecordId = null;
  }

  function textBlock(value) {
    const element = document.createElement("div");
    element.className = "seedpass-text";
    element.textContent = value;
    return element;
  }

  function findPasswordInput() {
    const inputs = Array.from(document.querySelectorAll('input[type="password"]'));
    const visible = inputs.filter(isFillablePasswordInput);
    return visible.find((input) => input === document.activeElement) ?? visible[0] ?? null;
  }

  function isFillablePasswordInput(element) {
    if (!(element instanceof HTMLInputElement) || element.type !== "password") return false;
    const rect = element.getBoundingClientRect();
    const style = window.getComputedStyle(element);
    return (
      rect.width > 0 &&
      rect.height > 0 &&
      style.visibility !== "hidden" &&
      style.display !== "none" &&
      !element.disabled &&
      !element.readOnly
    );
  }

  function fillInput(input, value) {
    if (!input || !value) return;
    const descriptor =
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value") ??
      Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input), "value");
    descriptor?.set?.call(input, value);
    input.dispatchEvent(new Event("input", { bubbles: true }));
    input.dispatchEvent(new Event("change", { bubbles: true }));
  }

  async function sendMessage(message) {
    const response = await chrome.runtime.sendMessage(message);
    if (!response?.ok) throw new Error(response?.error ?? text[currentLanguage].requestFailed);
    return response;
  }

  function resolveLanguage(value) {
    if (value === "en") return "en";
    if (value === "zh") return "zh";
    return navigator.language?.toLowerCase().startsWith("zh") ? "zh" : "en";
  }
}
