const WORDLIST = [
  "anchor", "apricot", "atlas", "bamboo", "beacon", "breeze", "cactus", "canyon",
  "cedar", "cinder", "cobalt", "coral", "cotton", "cricket", "delta", "ember",
  "falcon", "fennel", "forest", "galaxy", "garden", "harbor", "hazel", "helium",
  "island", "jacket", "juniper", "lantern", "lemon", "lizard", "magnet", "marble",
  "matrix", "meadow", "meteor", "nectar", "nickel", "oasis", "olive", "onyx",
  "orbit", "paddle", "paper", "pepper", "planet", "quartz", "rabbit", "raven",
  "river", "rocket", "saffron", "saturn", "silver", "sparrow", "spiral", "summit",
  "timber", "tundra", "velvet", "violet", "walnut", "willow", "winter", "zephyr"
];

const DEFAULT_POLICY = {
  length: 20,
  lowercase: true,
  uppercase: true,
  digits: true,
  symbols: true
};

const I18N = {
  zh: {
    title: "离线种子密码",
    tabSite: "当前网站",
    tabRecords: "密码列表",
    setupTitle: "创建本地保险库",
    seedLabel: "基密码：助记词、句子或任意语言文本",
    seedHint: "你可以使用生成的 24 个英文词，也可以输入中文、英文或任何语言的一句话。请保证它足够长、私密且可记忆。",
    generateSeed: "生成 24 词助记词",
    setPin: "设置 6 位数字 PIN",
    confirmPin: "再输入一次 PIN",
    unlockTimeout: "解锁有效期",
    saveUnlock: "加密保存并解锁",
    unlockTitle: "解锁保险库",
    enterPin: "输入 6 位 PIN",
    unlock: "解锁",
    detectedSite: "识别到的网站",
    siteRecords: "已保存记录",
    addRecord: "添加",
    searchRecords: "搜索记录",
    accountLabel: "账号标识",
    noteLabel: "密码备注",
    generationMode: "密码生成方式",
    modeDomain: "按网站生成",
    modeAccount: "仅按账号标识生成",
    length: "密码长度",
    lowercase: "小写",
    uppercase: "大写",
    digits: "数字",
    symbols: "符号",
    saveRecord: "保存",
    cancel: "取消",
    delete: "删除",
    lockNow: "立即锁定",
    fill: "填充",
    edit: "编辑",
    noVault: "还没有本地保险库，请先创建。",
    locked: "保险库已锁定。",
    unlockedUntil: "已解锁，有效至",
    noRecords: "当前网站还没有记录。添加一条后，密码框聚焦时会显示填充建议。",
    noSearch: "没有匹配的记录。",
    recordSaved: "记录已保存。",
    recordDeleted: "记录已删除。",
    filled: "密码已填充。",
    lockedNow: "已锁定。",
    vaultReady: "保险库已加密保存并解锁。",
    unlocked: "已解锁。",
    pinMismatch: "两次输入的 PIN 不一致。",
    pinRequired: "请输入 6 位数字 PIN。",
    editorNew: "添加密码记录",
    editorEdit: "编辑密码记录",
    domainHelp: "当前记录按网站生成密码。换设备时请输入这个网站名来复现同一个密码。账号标识和备注只用于管理，不会改变密码。",
    accountHelp: "当前记录仅按账号标识生成密码。换设备时请输入这个账号标识来复现同一个密码。记录仍会绑定到当前网站下展示。",
    domainBadge: "按网站生成",
    accountBadge: "按账号标识生成"
  },
  en: {
    title: "Offline Seed Passwords",
    tabSite: "Current site",
    tabRecords: "Records",
    setupTitle: "Create local vault",
    seedLabel: "Seed: phrase, sentence, or any-language text",
    seedHint: "Use the generated 24 English words, or enter a private memorable sentence in Chinese, English, or any language.",
    generateSeed: "Generate 24-word seed",
    setPin: "Set 6-digit PIN",
    confirmPin: "Confirm PIN",
    unlockTimeout: "Unlock timeout",
    saveUnlock: "Encrypt and unlock",
    unlockTitle: "Unlock vault",
    enterPin: "Enter 6-digit PIN",
    unlock: "Unlock",
    detectedSite: "Detected site",
    siteRecords: "Saved records",
    addRecord: "Add",
    searchRecords: "Search records",
    accountLabel: "Account label",
    noteLabel: "Note",
    generationMode: "Password is generated by",
    modeDomain: "Use website name",
    modeAccount: "Use account label only",
    length: "Length",
    lowercase: "lowercase",
    uppercase: "uppercase",
    digits: "digits",
    symbols: "symbols",
    saveRecord: "Save",
    cancel: "Cancel",
    delete: "Delete",
    lockNow: "Lock now",
    fill: "Fill",
    edit: "Edit",
    noVault: "No local vault yet. Create one first.",
    locked: "Vault locked.",
    unlockedUntil: "Unlocked until",
    noRecords: "No record for this site yet. Add one to show fill suggestions on password fields.",
    noSearch: "No matching records.",
    recordSaved: "Record saved.",
    recordDeleted: "Record deleted.",
    filled: "Password filled.",
    lockedNow: "Locked.",
    vaultReady: "Vault encrypted and unlocked.",
    unlocked: "Unlocked.",
    pinMismatch: "PIN confirmation does not match.",
    pinRequired: "Enter a 6-digit PIN.",
    editorNew: "Add password record",
    editorEdit: "Edit password record",
    domainHelp: "This record is generated by the website name. On another device, enter this website name to reproduce the same password. Account label and note are only for organization.",
    accountHelp: "This record is generated by account label only. On another device, enter this account label to reproduce the same password. It still appears under this website for convenience.",
    domainBadge: "Generated by site",
    accountBadge: "Generated by account"
  }
};

const elements = Object.fromEntries(
  [
    "status", "message", "language", "setup-view", "unlock-view", "site-view", "records-view",
    "editor-view", "setup-secret", "setup-timeout", "unlock-timeout", "site-identity",
    "site-help", "site-records", "all-records", "record-search", "editor-title",
    "record-id", "record-site", "record-account", "record-note", "mode-help",
    "policy-length", "policy-lowercase", "policy-uppercase", "policy-digits", "policy-symbols",
    "delete-record"
  ].map((id) => [camel(id), document.getElementById(id)])
);

const pinGroups = {
  setup: createPinBoxes("setup"),
  setupConfirm: createPinBoxes("setupConfirm"),
  unlock: createPinBoxes("unlock")
};

let language = "zh";
let currentSite = null;
let siteRecords = [];
let allRecords = [];
let activeTab = "site";

document.getElementById("generate-secret").addEventListener("click", () => {
  elements.setupSecret.value = generateMnemonic(24);
});
document.getElementById("setup-submit").addEventListener("click", setupVault);
document.getElementById("unlock-submit").addEventListener("click", unlockVault);
document.getElementById("lock-submit").addEventListener("click", lockVault);
document.getElementById("new-site-record").addEventListener("click", () => openEditor());
document.getElementById("save-record").addEventListener("click", saveRecord);
document.getElementById("cancel-edit").addEventListener("click", closeEditor);
document.getElementById("delete-record").addEventListener("click", deleteRecord);
elements.recordSearch.addEventListener("input", renderAllRecords);
elements.language.addEventListener("change", async () => {
  await sendMessage({ type: "set-language", language: elements.language.value });
  await loadLanguage();
  render();
});
for (const button of document.querySelectorAll(".tab")) {
  button.addEventListener("click", () => {
    activeTab = button.dataset.tab;
    render();
  });
}
for (const radio of document.querySelectorAll('input[name="record-mode"]')) {
  radio.addEventListener("change", updateModeHelp);
}
for (const box of pinGroups.unlock) box.addEventListener("seedpass-pin-complete", unlockVault);

await loadLanguage();
await refresh();

async function refresh() {
  const state = await sendMessage({ type: "get-state" });
  document.querySelector(".tabs").classList.toggle("hidden", !state.hasVault || !state.unlocked);
  elements.setupView.classList.toggle("hidden", state.hasVault);
  elements.unlockView.classList.toggle("hidden", !state.hasVault || state.unlocked);
  if (!state.hasVault) {
    elements.siteView.classList.add("hidden");
    elements.recordsView.classList.add("hidden");
    elements.editorView.classList.add("hidden");
    elements.status.textContent = t("noVault");
    focusPin("setup");
    return;
  }
  if (!state.unlocked) {
    elements.siteView.classList.add("hidden");
    elements.recordsView.classList.add("hidden");
    elements.editorView.classList.add("hidden");
    elements.status.textContent = t("locked");
    focusPin("unlock");
    return;
  }
  elements.status.textContent = `${t("unlockedUntil")} ${new Date(state.unlockedUntil).toLocaleTimeString(resolveLocale())}`;
  await loadRecords();
  render();
}

async function loadRecords() {
  const siteResponse = await sendMessage({ type: "get-site-records" });
  currentSite = siteResponse.site;
  siteRecords = siteResponse.records;
  allRecords = (await sendMessage({ type: "get-all-records" })).records;
}

function render() {
  applyI18n();
  document.querySelectorAll(".tab").forEach((button) => {
    button.classList.toggle("active", button.dataset.tab === activeTab);
  });
  elements.siteView.classList.toggle("hidden", activeTab !== "site");
  elements.recordsView.classList.toggle("hidden", activeTab !== "records");
  elements.editorView.classList.add("hidden");
  if (currentSite) {
    elements.siteIdentity.textContent = currentSite.identity;
    elements.siteHelp.textContent = t("domainHelp");
  }
  renderSiteRecords();
  renderAllRecords();
}

function renderSiteRecords() {
  elements.siteRecords.innerHTML = "";
  if (!siteRecords.length) {
    elements.siteRecords.append(emptyText(t("noRecords")));
    return;
  }
  siteRecords.forEach((record) => elements.siteRecords.append(recordCard(record)));
}

function renderAllRecords() {
  elements.allRecords.innerHTML = "";
  const query = elements.recordSearch.value.trim().toLowerCase();
  const records = allRecords.filter((record) =>
    [record.siteIdentity, record.accountLabel, record.note, record.mode]
      .join(" ")
      .toLowerCase()
      .includes(query)
  );
  if (!records.length) {
    elements.allRecords.append(emptyText(t("noSearch")));
    return;
  }
  records.forEach((record) => elements.allRecords.append(recordCard(record)));
}

function recordCard(record) {
  const card = document.createElement("div");
  card.className = "record-card";
  const title = record.accountLabel || record.siteIdentity;
  const badge = record.mode === "account" ? t("accountBadge") : t("domainBadge");
  card.innerHTML = `
    <small></small>
    <strong></strong>
    <span></span>
    <div class="record-actions"></div>
  `;
  card.querySelector("small").textContent = `${record.siteIdentity} · ${badge}`;
  card.querySelector("strong").textContent = title;
  card.querySelector("span").textContent = record.note || " ";
  const actions = card.querySelector(".record-actions");
  if (record.siteIdentity === currentSite?.identity) {
    actions.append(button(t("fill"), () => fillRecord(record.id)));
  }
  actions.append(button(t("edit"), () => openEditor(record), "secondary"));
  return card;
}

function openEditor(record = null) {
  const editing = Boolean(record?.id);
  const base = record ?? {
    siteIdentity: currentSite?.identity ?? "",
    accountLabel: "",
    note: "",
    mode: "domain",
    policy: DEFAULT_POLICY
  };
  elements.siteView.classList.add("hidden");
  elements.recordsView.classList.add("hidden");
  elements.editorView.classList.remove("hidden");
  elements.editorTitle.textContent = editing ? t("editorEdit") : t("editorNew");
  elements.recordId.value = base.id ?? "";
  elements.recordSite.value = base.siteIdentity;
  elements.recordAccount.value = base.accountLabel ?? "";
  elements.recordNote.value = base.note ?? "";
  document.querySelector(`input[name="record-mode"][value="${base.mode ?? "domain"}"]`).checked = true;
  writePolicy(base.policy ?? DEFAULT_POLICY);
  elements.deleteRecord.classList.toggle("hidden", !editing);
  updateModeHelp();
}

function closeEditor() {
  render();
}

async function saveRecord() {
  await runAction(async () => {
    const record = {
      id: elements.recordId.value,
      siteIdentity: elements.recordSite.value,
      accountLabel: elements.recordAccount.value.trim(),
      note: elements.recordNote.value.trim(),
      mode: document.querySelector('input[name="record-mode"]:checked').value,
      policy: readPolicy()
    };
    await sendMessage({ type: "save-record", record });
    await loadRecords();
    showMessage(t("recordSaved"));
    closeEditor();
  });
}

async function deleteRecord() {
  await runAction(async () => {
    await sendMessage({ type: "delete-record", recordId: elements.recordId.value });
    await loadRecords();
    showMessage(t("recordDeleted"));
    closeEditor();
  });
}

async function fillRecord(recordId) {
  await runAction(async () => {
    await sendMessage({ type: "fill-record", recordId });
    showMessage(t("filled"));
  });
}

async function setupVault() {
  await runAction(async () => {
    const pin = readPin("setup");
    if (pin !== readPin("setupConfirm")) throw new Error(t("pinMismatch"));
    await sendMessage({
      type: "setup-vault",
      baseSecret: elements.setupSecret.value,
      unlockPassword: pin,
      timeoutMinutes: Number(elements.setupTimeout.value)
    });
    clearPin("setup");
    clearPin("setupConfirm");
    await refresh();
    showMessage(t("vaultReady"));
  });
}

async function unlockVault() {
  await runAction(async () => {
    await sendMessage({
      type: "unlock",
      unlockPassword: readPin("unlock"),
      timeoutMinutes: Number(elements.unlockTimeout.value)
    });
    clearPin("unlock");
    await refresh();
    showMessage(t("unlocked"));
  });
}

async function lockVault() {
  await runAction(async () => {
    await sendMessage({ type: "lock" });
    await refresh();
    showMessage(t("lockedNow"));
  });
}

function updateModeHelp() {
  const mode = document.querySelector('input[name="record-mode"]:checked')?.value ?? "domain";
  elements.modeHelp.textContent = mode === "account" ? t("accountHelp") : t("domainHelp");
}

function readPolicy() {
  return {
    length: Number(elements.policyLength.value),
    lowercase: elements.policyLowercase.checked,
    uppercase: elements.policyUppercase.checked,
    digits: elements.policyDigits.checked,
    symbols: elements.policySymbols.checked
  };
}

function writePolicy(policy) {
  elements.policyLength.value = policy.length ?? DEFAULT_POLICY.length;
  elements.policyLowercase.checked = policy.lowercase ?? DEFAULT_POLICY.lowercase;
  elements.policyUppercase.checked = policy.uppercase ?? DEFAULT_POLICY.uppercase;
  elements.policyDigits.checked = policy.digits ?? DEFAULT_POLICY.digits;
  elements.policySymbols.checked = policy.symbols ?? DEFAULT_POLICY.symbols;
}

function createPinBoxes(name) {
  const row = document.querySelector(`[data-pin="${name.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)}"]`);
  const boxes = Array.from({ length: 6 }, (_, index) => {
    const input = document.createElement("input");
    input.type = "password";
    input.inputMode = "numeric";
    input.maxLength = 1;
    input.autocomplete = "off";
    input.className = "pin-box";
    input.ariaLabel = `PIN ${index + 1}`;
    row.append(input);
    return input;
  });
  boxes.forEach((box, index) => {
    box.addEventListener("input", () => {
      box.value = box.value.replace(/\D/g, "").slice(0, 1);
      if (box.value && index < boxes.length - 1) boxes[index + 1].focus();
      if (/^\d{6}$/.test(readPinByBoxes(boxes))) box.dispatchEvent(new Event("seedpass-pin-complete"));
    });
    box.addEventListener("keydown", (event) => {
      if (event.key === "Backspace" && !box.value && index > 0) boxes[index - 1].focus();
    });
  });
  return boxes;
}

function readPin(name) {
  const pin = readPinByBoxes(pinGroups[name]);
  if (!/^\d{6}$/.test(pin)) throw new Error(t("pinRequired"));
  return pin;
}

function readPinByBoxes(boxes) {
  return boxes.map((box) => box.value).join("");
}

function clearPin(name) {
  pinGroups[name].forEach((box) => (box.value = ""));
}

function focusPin(name) {
  setTimeout(() => pinGroups[name][0]?.focus(), 0);
}

async function loadLanguage() {
  const response = await sendMessage({ type: "get-language" });
  elements.language.value = response.language;
  language = resolveLanguage(response.language);
  document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  applyI18n();
}

function applyI18n() {
  language = resolveLanguage(elements.language.value);
  for (const node of document.querySelectorAll("[data-i18n]")) {
    node.textContent = t(node.dataset.i18n);
  }
  updateModeHelp();
}

function resolveLanguage(value) {
  if (value === "zh") return "zh";
  if (value === "en") return "en";
  return navigator.language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

function resolveLocale() {
  return language === "zh" ? "zh-CN" : "en-US";
}

function t(key) {
  return I18N[language][key] ?? I18N.en[key] ?? key;
}

async function runAction(action) {
  setBusy(true);
  showMessage("");
  try {
    await action();
  } catch (error) {
    showMessage(error.message, true);
  } finally {
    setBusy(false);
  }
}

function setBusy(busy) {
  document.querySelectorAll("button").forEach((item) => (item.disabled = busy));
}

function showMessage(message, isError = false) {
  elements.message.textContent = message;
  elements.message.style.color = isError ? "#9f1d16" : "#685842";
}

function button(label, onClick, className = "") {
  const item = document.createElement("button");
  item.type = "button";
  item.className = className;
  item.textContent = label;
  item.addEventListener("click", onClick);
  return item;
}

function emptyText(value) {
  const item = document.createElement("p");
  item.className = "hint";
  item.textContent = value;
  return item;
}

async function sendMessage(message) {
  const response = await chrome.runtime.sendMessage(message);
  if (!response?.ok) throw new Error(response?.error ?? "Request failed / 请求失败。");
  return response;
}

function generateMnemonic(words) {
  const bytes = crypto.getRandomValues(new Uint8Array(words));
  return Array.from({ length: words }, (_, index) => WORDLIST[bytes[index] % WORDLIST.length]).join(" ");
}

function camel(id) {
  return id.replace(/-([a-z])/g, (_, char) => char.toUpperCase());
}
